version: "3"
services:
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "default"
    environment:
     NEO4J_AUTH: neo4j/jack
  php:
    depends_on:
      - "frontend"
      - "neo4j"
    build:
      context: "."
      dockerfile: "docker/php.Dockerfile"
    ports:
      - "8080:80"
    networks:
      - "default"
    volumes:
      - "./learning_made_easy:/var/www/html"
  composer:
    image: "composer:1.8"
    volumes:
      - "./learning_made_easy:/app"
      - "~/.composer:/tmp"
    command: "composer about"
    networks:
      - "default"
  frontend:
    build:
      context: "."
      dockerfile: "docker/frontend.Dockerfile"
    expose:
      - "4000"
    ports:
      - "4000:3000"
    volumes:
      - "./front-end/src:/usr/src/app/src"
      - "./front-end/public:/usr/src/app/public"
    networks:
      - "default"
networks:
  default:
