version: "3"
services:
  neo4j:
    container_name: 'neo4j-final'
    image: "neo4j:3.5.14"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "default"
    environment:
     NEO4J_AUTH: neo4j/jack
     NEO4J_dbms_active_database: neo4j.db
     NEO4J_dbms_security_procedures_unrestricted: algo.*
     NEO4J_dbms_security_procedures_whitelist: algo.*
     NEO4J_dbms_directories_plugins: plugins
    volumes:
      - "./back/neo4j-graph-algorithms-3.5.14.0-standalone.jar:/var/lib/neo4j/plugins/neo4j-graph-algorithms-3.5.14.0-standalone.jar"
  php:
    depends_on:
      - "neo4j"
    image: jack529/easylearn_php:easylearn
    ports:
      - "9501:9501"
    command: tail -f /dev/null
    networks:
      - "default"
    volumes:
      - "./learning_made_easy:/var/www/html"
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    networks:
      - "default"
  frontend:
    build:
      context: "."
      dockerfile: "docker/frontend.Dockerfile"
    expose:
      - "4000"
    ports:
      - "4000:3000"
    volumes:
      - "./front-end/src:/usr/src/app/src"
      - "./front-end/public:/usr/src/app/public"
    networks:
      - "default"
  minio:
    image: "3sidedcube/minio"
    networks:
      - "default"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "AKIABUVWH1HUD7YQZQAR"
      MINIO_SECRET_KEY: "PVMlDMep3/jLSz9GxPV3mTvH4JZynkf2BFeTu+i8"
networks:
  default:
