framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    trusted_hosts:
        - localhost
        - easylearn.live
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    session:
        handler_id: ~
        storage_id: session.storage.php_bridge
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
