create_user:
    path: /api/register
    controller: App\Controller\UserController::create
    methods: POST

me:
    path: /api/me
    controller: App\Controller\UserController::index
    methods: POST

api_login_check:
    path: /api/login
    defaults: { _controller: App\Controller\TokenController::Token }
    methods: ['POST']

create_course:
    path: /api/course
    controller: App\Controller\CourseController::create
    methods: POST

create_learning_resource:
    path: /api/coure-resource
    controller: App\Controller\LearningResourceController::upload
    methods: POST

create_learning_resources:
    path: /api/coure-resources
    controller: App\Controller\LearningResourceController::index
    methods: POST

users_active:
    path: /api/next-active
    controller: App\Controller\LearningResourceController::userFindFirst
    methods: GET

get_learning_resource:
    path: /api/coure-resource
    controller: App\Controller\LearningResourceController::getS3
    methods: GET

learning_style:
    path: /api/learning-style
    controller: App\Controller\LearningQuizController::Calculate
    methods: Post

user_time:
    path: /api/user-time
    controller: App\Controller\UserController::saveTime
    methods: Post

user_course:
    path: /api/user-course
    controller: App\Controller\CourseController::getAllCoursesYouCreated
    methods: get

all_courses_resources:
    path: /api/courses
    controller: App\Controller\CourseController::getAll
    methods: get

which_course:
    path: /api/courses
    controller: App\Controller\CourseController::studyingNow
    methods: post


consume_course:
    path: /api/consume
    controller: App\Controller\LearningResourceController::consumeLearningResource
    methods: post

course_analytics:
    path: /api/course-analytics
    controller: App\Controller\LearningAnalyticsController::getAnalytics
    methods: GET

